version: "3.7"
services:

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=2020
    networks:
      - microservices

networks:
  microservices:
    name: microservices