version: "3.7"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "2020"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=2020

volumes:
  pgdata: {}
networks:
  postgres_network:
    name: postgres_net
    driver: bridge