version: "3.7"
services:

  grafana:
    container_name: grafana
    image: 'grafana/grafana'
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: 'prom/prometheus'
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring