version: "3.7"
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-input_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "2020"
      PGDATA: /var/lib/volumen/data/pgdata
    ports:
      - 3306:3306
    volumes:
      - pgdata:/var/lib/volumen/data
    networks:
      - microservices

    #  java:
      #build:
      #context: .
      #dockerfile: docker-compose.yaml
      #depends_on:
      #- postgres
      #networks:
      #- microservices
      #ports:
      #- 8081:8081

volumes:
  pgdata: {}
networks:
  microservices:
    external:
      name: microservices